export const ERROR_CODES = {
  CASE_REVISION_CONFLICT: 'CASE_REVISION_CONFLICT',
  REVIEWER_CONFIRMATION_REQUIRED: 'REVIEWER_CONFIRMATION_REQUIRED',
  FACT_SOURCE_REQUIRED: 'FACT_SOURCE_REQUIRED',
  NEGATIVE_FACT_SCOPE_REQUIRED: 'NEGATIVE_FACT_SCOPE_REQUIRED',
  HYPOTHESIS_FALSIFICATION_REQUIRED: 'HYPOTHESIS_FALSIFICATION_REQUIRED',
  DECISION_SUPPORT_REQUIRED: 'DECISION_SUPPORT_REQUIRED'
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];